Test db migration to bmds
shapiromatron/bmds-archive pull request #55
Opened 2021-09-07 16:49 UTC by bishwobhandari

added packages to bmds repo

2021-09-13 18:13 UTC, bishwobhandari commented
@shapiromatron, could you please review the run_analysis method on bmds/benchmarks/main.py? run_analysis is called from a jupyter notebook file bmds/benchmarks/api.ipynb like eg:  run_analysis("TOXREFDB_DICH", ["bmds2", "bmds3"], True)

2021-09-13 18:20 UTC, shapiromatron requested changes
preliminary review

2021-09-13 18:20 UTC, shapiromatron commented on bmds/benchmarks/api.ipynb
> +{
can you move this file to `notesbooks/benchmarks.ipynb`?

2021-09-13 18:20 UTC, shapiromatron commented on .gitignore
> +bmds/benchmarks/toxrefdb/app/app.db
change to *.db and add to the files section

2021-09-13 18:20 UTC, shapiromatron commented on bmds/benchmarks/README.md
> +# bmds data comparison
Remove this section please? Take the good stuff and move above. Could you please write in complete sentences instead of bullets?

2021-09-13 18:20 UTC, shapiromatron commented on bmds/benchmarks/main.py
> +    BMDS270 = "bmds2"
change the values to `bmds270` and `bmds330`

2021-09-13 18:20 UTC, shapiromatron commented on bmds/benchmarks/main.py
> +    for version in versions:
how are datasets loaded or handled here? do we need another method that bulk loads datasets?

2021-09-13 18:20 UTC, shapiromatron commented on bmds/benchmarks/toxrefdb/app/shared.py
> +def _execute_bmds2_model(model, model_name, dataset, version):
should this be `_execute_bmds270_model` and bmds330 below?

2021-09-13 18:20 UTC, shapiromatron commented on bmds/benchmarks/toxrefdb/continuous.py
> +class ContinuousModel(Enum):
this Enum is probably unnecessary; I think these are the values in `bmds.constants.M_Power`?

2021-09-13 18:20 UTC, shapiromatron commented on bmds/benchmarks/toxrefdb/dichotomous.py
> +class DichotomousModel(Enum):
like above, this Enum is probably unnecessary; they should be in bmds.constants..

2021-09-13 18:20 UTC, shapiromatron commented on bmds/benchmarks/toxrefdb/migrations/README
> +Generic single-database configuration.
remove this file

2021-09-13 18:20 UTC, shapiromatron commented on bmds/benchmarks/README.md
> +# bmds data comparison
I think you had some issues with dropping/loading data, as well as steps that may be required to `init` the database. could you add these to the readme as well?

2021-09-13 18:24 UTC, shapiromatron commented
> @shapiromatron, could you please review the run_analysis method on bmds/benchmarks/main.py? run_analysis is called from a jupyter notebook file bmds/benchmarks/api.ipynb like eg: run_analysis("TOXREFDB_DICH", ["bmds2", "bmds3"], True)

I think we should call using the enums you defined instead of throwing around strings, for example:

```python
from bmds.benchmarks.main import Dataset, Versions

run_analysis(Dataset.TOXREFDB_DICH, [Versions.BMDS270, Versions.BMDS330], True)
```

2021-09-13 18:52 UTC, bishwobhandari commented on bmds/benchmarks/api.ipynb
> +{
moved to notebooks/benchmarks.ipynb

2021-09-13 19:00 UTC, bishwobhandari commented on bmds/benchmarks/main.py
> +    BMDS270 = "bmds2"
changed to  bmds270 and bmds330

2021-09-14 21:21 UTC, bishwobhandari commented on bmds/benchmarks/toxrefdb/migrations/README
> +Generic single-database configuration.
removed

2021-09-14 21:22 UTC, bishwobhandari commented on bmds/benchmarks/toxrefdb/dichotomous.py
> +class DichotomousModel(Enum):
replaced with bmds.constants.

2021-09-14 21:22 UTC, bishwobhandari commented on bmds/benchmarks/toxrefdb/continuous.py
> +class ContinuousModel(Enum):
replaced with bmds.constants.

2021-09-14 21:22 UTC, bishwobhandari commented on bmds/benchmarks/toxrefdb/app/shared.py
> +def _execute_bmds2_model(model, model_name, dataset, version):
changed to bmds270 and bmds330

2021-09-14 21:23 UTC, bishwobhandari commented on bmds/benchmarks/main.py
> +    for version in versions:
datasets are loaded through load_dataset method by the user with dataset and filename as parameters. 
e.g Benchmark.load_dataset(Dataset.TOXREFDB_DICH, "dichotomous_tr.csv")

2021-09-14 21:23 UTC, bishwobhandari commented on bmds/benchmarks/README.md
> +# bmds data comparison
updated read me file

2021-09-14 21:26 UTC, bishwobhandari commented
@shapiromatron please review the run_analysis method. if the dataset table does not exist or dataset does not exist in the table it throws error and gives user a message. then user will have to create db or load dataset based on the message. i removed the jupyter notebook file. so from command line you can execute like this. 

from bmds.benchmarks.main import Dataset, Versions, Benchmark
Benchmark.run_analysis(Dataset.TOXREFDB_DICH, [Versions.BMDS270], True)

2021-10-05 19:01 UTC, shapiromatron approved these changes
Made some changes, but asking for @rabstejnek to review to see how it works and flows on another computer.

2021-10-18 20:00 UTC, rabstejnek approved these changes
Followed the instructions on my Windows machine, looks good!

2021-10-20 14:01 UTC, merged